#!/usr/bin/env node
/**
 * Generate the cross-language golden file from the shared corpus.
 *
 * The sanitizer's logic lives once, in `src/`. This records `sanitize`'s output
 * for each corpus case (both `html:false` and `html:true`) so the Python client
 * — which shells out to the same `src/` via the CLI — can be asserted
 * byte-for-byte equal against it (`tests/test_python_client.py`). Inputs and
 * recorded `cleaned` text travel as arrays of UTF-16 code units, not JSON
 * strings, so lone surrogates and astral characters round-trip identically in
 * both languages (a JSON string can't carry a lone surrogate losslessly, and an
 * astral char is one Python code point but two JS code units — code units are
 * the common currency both sides reconstruct identically).
 *
 * Run from the repo root: `node test/generate-golden.mjs`. The committed output
 * (`tests/golden.json`) is regenerated and the diff reviewed; the JS golden test
 * (`test/golden-corpus.test.mjs`) fails if the committed file drifts from a
 * fresh run, so this stays in lockstep with `src/`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import prettier from "prettier";

import { sanitize } from "../src/index.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const corpusPath = join(repoRoot, "tests", "golden-corpus.json");
const goldenPath = join(repoRoot, "tests", "golden.json");

/** Reconstruct a string from an array of UTF-16 code units. fromCharCode per
 * unit keeps lone surrogates and astral surrogate pairs exact. */
function fromUnits(units) {
  return units.map((u) => String.fromCharCode(u)).join("");
}

/** A string to its array of UTF-16 code units (one per `.length` index, so an
 * astral char becomes its two surrogates). This survives JSON even when the
 * text contains a lone surrogate, where a JSON string could not. */
function toUnits(text) {
  const units = [];
  for (let i = 0; i < text.length; i++) units.push(text.charCodeAt(i));
  return units;
}

async function buildGolden() {
  const corpus = JSON.parse(readFileSync(corpusPath, "utf8"));
  const cases = [];
  for (const { name, units } of corpus.cases) {
    const input = fromUnits(units);
    const record = {};
    for (const html of [false, true]) {
      const result = await sanitize(input, { html });
      record[html ? "html" : "plain"] = {
        cleaned: toUnits(result.cleaned),
        found: result.found,
        warnings: result.warnings,
      };
    }
    cases.push({ name, ...record });
  }
  return {
    _comment:
      "GENERATED by test/generate-golden.mjs from tests/golden-corpus.json. " +
      "Do not hand-edit. `cleaned` is an array of UTF-16 code units so lone " +
      "surrogates and astral chars round-trip; reconstruct with " +
      "String.fromCharCode (JS) or by combining surrogate pairs (Python).",
    cases,
  };
}

const golden = await buildGolden();
// Format through prettier (resolving the repo config) so the committed file is
// prettier-clean by construction — the format check and the freshness check
// then agree, with this generator's output as the single source of truth.
const serialized = await prettier.format(JSON.stringify(golden), {
  ...(await prettier.resolveConfig(goldenPath)),
  parser: "json",
});

if (process.argv.includes("--check")) {
  const existing = readFileSync(goldenPath, "utf8");
  if (existing !== serialized) {
    process.stderr.write(
      "tests/golden.json is stale; regenerate with `node test/generate-golden.mjs`.\n",
    );
    process.exit(1);
  }
} else {
  writeFileSync(goldenPath, serialized);
  process.stdout.write(`wrote ${goldenPath} (${golden.cases.length} cases)\n`);
}
